);
// person.set("firstName","Paras");
// person.set("age",20);
// console.log(person);
// person.set(1, "one");
// person.set([1, 2, 3], "onetwothree");
// person.set({1:"two"}, "onetwothree");
// console.log(person);
// console.log(person.get('firstName'));
// console.log(person.get(1));